# Generated by Django 5.0.1 on 2024-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
